import dynamic from "next/dynamic";

const Editor = dynamic(() => import("../_components/block-note"), {
  ssr: false,
});

export default function Page() {
  return (
    <main>
      <Editor />
    </main>
  );
}
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
